name: Android Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: MyTonWallet
  PROXY_HOSTS: ${{ vars.PROXY_HOSTS }}
  STAKING_POOLS: ${{ vars.STAKING_POOLS }}
  PUBLISH_REPO: ${{ vars.PUBLISH_REPO }}

jobs:
  android-release:
    name: Release Android app
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    if: github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare the Node environment
        uses: ./.github/actions/prepare_node
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Build and sync mobile project
        run: |
          if [ -z "$PUBLISH_REPO" ]; then
            npm run mobile:build:staging
          else
            npm run mobile:build:production
          fi

      - name: Use Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
          working-directory: mobile

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Package and publish
        env:
          ANDROID_API_KEY_BASE64: ${{ secrets.ANDROID_API_KEY_BASE64 }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: |
          cd mobile/android

          echo -n "$ANDROID_API_KEY_BASE64" | base64 --decode > ./api-key.json
          echo -n "$ANDROID_KEYSTORE_BASE64" | base64 --decode > ./android.keystore

          if [ -z "$PUBLISH_REPO" ]; then
            bundle exec fastlane beta
          else
            bundle exec fastlane release
          fi

      - name: Build project for direct apk
        env:
          IS_ANDROID_DIRECT: 1
        run: |
          if [ -z "$PUBLISH_REPO" ]; then
            npm run mobile:build:staging
          else
            npm run mobile:build:production
          fi

      - name: Build direct apk
        env:
          ANDROID_API_KEY_BASE64: ${{ secrets.ANDROID_API_KEY_BASE64 }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: |
          cd mobile/android
          bundle exec fastlane direct
          cd ../../
          mv mobile/android/app/build/outputs/apk/release/app-release.apk $APP_NAME.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}.apk
          path: ${{ env.APP_NAME }}.apk

  publish-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    needs:
      - android-release
    if: github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/master' && vars.PUBLISH_REPO != ''
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set environment variables
        id: variables
        run: |
          echo "ANDROID_FILE_NAME=${{ env.APP_NAME }}.apk" >> "$GITHUB_ENV"

      - name: Download Android package
        id: download-android
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ANDROID_FILE_NAME }}

      - name: Get latest release ID
        id: release-id
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/repos/$PUBLISH_REPO/releases?per_page=1" | jq -r '.[0].id')
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Delete existing asset
        env:
          RELEASE_ID: ${{ steps.release-id.outputs.release_id }}
        run: |
          PUBLISH_FILE_NAME=${ANDROID_FILE_NAME// /-}
          ASSET_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/repos/$PUBLISH_REPO/releases/$RELEASE_ID/assets" | jq -r --arg PUBLISH_FILE_NAME "$PUBLISH_FILE_NAME" '.[] | select(.name == $PUBLISH_FILE_NAME) | .id')
          curl -X DELETE -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/repos/$PUBLISH_REPO/releases/assets/$ASSET_ID"

      - name: Push new Android asset
        env:
          FILE_PATH: ${{ steps.download-android.outputs.download-path }}
          RELEASE_ID: ${{ steps.release-id.outputs.release_id }}
        run: |
          FILE_NAME=$ANDROID_FILE_NAME
          PUBLISH_FILE_NAME=${ANDROID_FILE_NAME// /-}
          curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@$FILE_PATH/$FILE_NAME" \
            "https://uploads.github.com/repos/$PUBLISH_REPO/releases/$RELEASE_ID/assets?name=$PUBLISH_FILE_NAME"

      - name: Publish release
        env:
          RELEASE_ID: ${{ steps.release-id.outputs.release_id }}
        run: |
          curl -X PATCH -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/repos/$PUBLISH_REPO/releases/$RELEASE_ID" -d '{"draft": false}'